<a href="https://colab.research.google.com/github/acarjunarju/python30days-workout/blob/main/day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [6]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])